#!/bin/sh
DIR=$(dirname $(readlink "$0") 2>/dev/null || dirname "$0" 2>/dev/null )
cd $DIR
TARGET=target/scala-2.11/classes
SRC_FILE=src/main/scala/MavenSearch.scala
mkdir -p $TARGET
if [ $SRC_FILE -nt $TARGET/MavenSearch.class ]
then
	scalac -d $TARGET $SRC_FILE
fi
scala -cp $TARGET MavenSearch $*
#chavxo.maven_search.MavenSearch $*
